apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-master
  name: spark-master
  namespace: de
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-py
          image: binayakd86/spark-py:v0.1
          command: ["/opt/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.master.Master"]
          env:
            - name: SPARK_MASTER_HOST
              value: "0.0.0.0"
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
            - name: SPARK_LOCAL_DIRS
              value: /tmp/scratch
            - name: SPARK_DAEMON_JAVA_OPTS
              value: "-Dspark.deploy.recoveryMode=FILESYSTEM -Dspark.deploy.recoveryDirectory=/recovery"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /recovery
              name: recovery
      volumes:
        - name: tmp
          emptyDir: {}
        - name: recovery
          nfs:
            server: 192.168.0.101
            path: "/root/cluster-data/spark-master-recovery"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: de
spec:
  selector:
    app: spark-master
  ports:
  - name: spark
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: webui
    protocol: TCP
    port: 8080
    targetPort: 8080