apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-ui-proxy
  name: spark-ui-proxy
  namespace: de
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-ui-proxy
  template:
    metadata:
      labels:
        app: spark-ui-proxy
    spec:
      containers:
        - name: spark-ui-proxy
          image: binayakd86/spark-ui-proxy:v0.1
          args:
            - spark-master:8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-ui-proxy
  namespace: de
spec:
  selector:
    app: spark-ui-proxy
  ports:
  - name: proxy
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ui-proxy
  namespace: de
  labels:
    app: spark-ui-proxy
spec:
  rules:
    - host: spark.192.168.0.101.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spark-ui-proxy
                port:
                  number: 80
