apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-master
  namespace: de
  labels:
    app: spark-master
spec:
  rules:
    - host: spark.192.168.0.101.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spark-master
                port:
                  number: 8080
